spring:
  jpa:
    generate-ddl: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: PKS@89@pks
  mvc.view:
    prefix: /WEB-INF/
    suffix: .jsp
s3:
  endpointUrl: http://127.0.0.1:9000
  accessKey: YOB9LF5VORI6Z0MBYTD6
  secretKey: hFty1O3B92Kbu8LlP1wRpsuPKLw1L0DT2ptj4HW2
  bucketName: moviefun
